version: "3"

services:
  app:
    build:
      context: app
    ports:
      - "4455"

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
